# Generated by Django 5.0.2 on 2024-03-29 00:02

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required and unique', max_length=255, unique=True)),
                ('slug', models.SlugField(help_text='Category safe URL', max_length=255, unique=True)),
                ('category_sku', models.CharField(blank=True, help_text='Defaults to slug if left blank', max_length=255, null=True, verbose_name='Category SKU')),
                ('is_featured', models.BooleanField(default=False)),
                ('ordering', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='store.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('ordering',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Featured product name', max_length=255, unique=True)),
                ('slug', models.SlugField(help_text='Category safe URL', max_length=255, unique=True)),
                ('product_sku', models.CharField(blank=True, help_text='Defaults to slug if left blank', max_length=255, null=True, verbose_name='Product SKU')),
                ('description', models.TextField(blank=True, help_text='Not Required', max_length=10000, null=True, verbose_name='Description')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum 9999999.99', max_digits=9, null=True, verbose_name='Base Price')),
                ('is_featured', models.BooleanField(default=False)),
                ('ordering', models.IntegerField(default=0)),
                ('num_visits', models.IntegerField(default=0)),
                ('last_visit', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated on')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='store.product')),
            ],
            options={
                'ordering': ('ordering',),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/product/images/')),
                ('thumbnail', models.ImageField(blank=True, help_text='Automatically generated, do not need to upload', null=True, upload_to='uploads/product/thumbnails/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('stars', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/product_reviews/images/')),
                ('thumbnail', models.ImageField(blank=True, help_text='Automatically generated, do not need to upload', null=True, upload_to='uploads/product_reviews/images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product Review',
                'verbose_name_plural': 'Product Reviews',
            },
        ),
        migrations.CreateModel(
            name='VariationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Variation Categories - Required if there are options', max_length=255, unique=True)),
                ('slug', models.SlugField(help_text='Category safe URL', max_length=255, unique=True)),
                ('variation_sku', models.CharField(blank=True, help_text='Defaults to slug if left blank', max_length=255, null=True, verbose_name='Variation SKU')),
                ('description', models.TextField(blank=True, help_text='Not Required', max_length=10000, null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/variation/images/')),
                ('thumbnail', models.ImageField(blank=True, help_text='Automatically generated, do not need to upload', null=True, upload_to='uploads/variation/thumbnails/')),
                ('ordering', models.IntegerField(default=0)),
                ('level', models.PositiveIntegerField(default=0)),
                ('lft', models.PositiveIntegerField(default=0)),
                ('rght', models.PositiveIntegerField(default=0)),
                ('tree_id', models.PositiveIntegerField(default=0)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='store.variationcategory')),
                ('product', models.ManyToManyField(related_name='variation', to='store.product')),
            ],
            options={
                'verbose_name': 'Variation',
                'verbose_name_plural': 'Variations',
            },
        ),
        migrations.CreateModel(
            name='VariationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_text', models.CharField(blank=True, help_text='Add alternative text', max_length=255, null=True, verbose_name='Alternative text')),
                ('name', models.CharField(help_text='Variation Option - not required', max_length=255, unique=True)),
                ('slug', models.SlugField(help_text='Category safe URL', max_length=255, unique=True)),
                ('option_sku', models.CharField(blank=True, help_text='Defaults to slug if left blank', max_length=255, null=True, verbose_name='Option SKU')),
                ('description', models.TextField(blank=True, help_text='Not Required', max_length=10000, null=True, verbose_name='Description')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum 9999999.99', max_digits=9, null=True, verbose_name='Base Price')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/option/images/')),
                ('thumbnail', models.ImageField(blank=True, help_text='Automatically generated, do not need to upload', null=True, upload_to='uploads/option/thumbnails/')),
                ('ordering', models.IntegerField(default=0)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='store.variationoption')),
                ('product', models.ManyToManyField(related_name='option', to='store.product')),
                ('variation', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='option', to='store.variationcategory')),
            ],
            options={
                'verbose_name': 'Option',
                'verbose_name_plural': 'Options',
            },
        ),
        migrations.CreateModel(
            name='VariationSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_text', models.CharField(blank=True, help_text='Add alternative text', max_length=255, null=True, verbose_name='Alternative text')),
                ('name', models.CharField(help_text='Variation Specifications - not required', max_length=255, unique=True)),
                ('slug', models.SlugField(help_text='Category safe URL', max_length=255, unique=True)),
                ('specification_sku', models.CharField(blank=True, help_text='Defaults to slug if left blank', max_length=255, null=True, verbose_name='Specification SKU')),
                ('description', models.TextField(blank=True, help_text='Not Required', max_length=10000, null=True, verbose_name='Description')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum 9999999.99', max_digits=9, null=True, verbose_name='Base Price')),
                ('num_available', models.IntegerField(blank=True, default=None, null=True)),
                ('is_featured', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/specification/images/')),
                ('thumbnail', models.ImageField(blank=True, help_text='Automatically generated, do not need to upload', null=True, upload_to='uploads/specification/thumbnails/')),
                ('ordering', models.IntegerField(default=0)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('option', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='specification', to='store.variationoption')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='store.variationspecification')),
                ('product', models.ManyToManyField(related_name='specification', to='store.product')),
            ],
            options={
                'verbose_name': 'Specification',
                'verbose_name_plural': 'Specifications',
            },
        ),
    ]
