# Generated by Django 5.0.2 on 2024-03-06 08:14

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Required and unique', max_length=255, unique=True)),
                ('slug', models.SlugField(help_text='Category safe URL', max_length=255, unique=True)),
                ('category_sku', models.CharField(blank=True, help_text='Defaults to slug if left blank', max_length=255, null=True, verbose_name='Category SKU')),
                ('is_featured', models.BooleanField(default=False)),
                ('ordering', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='store.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('ordering',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_text', models.CharField(blank=True, help_text='Add alternative text', max_length=255, null=True, verbose_name='Alternative text')),
                ('title', models.CharField(help_text='Featured product name', max_length=255, unique=True)),
                ('slug', models.SlugField(help_text='Category safe URL', max_length=255, unique=True)),
                ('product_sku', models.CharField(blank=True, help_text='Defaults to slug if left blank', max_length=255, null=True, verbose_name='Product SKU')),
                ('description', models.TextField(blank=True, help_text='Not Required', max_length=10000, null=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, error_messages={'name': {'max_length': 'The price must be between 0 and 9999999.99'}}, help_text='Maximum 9999999.99', max_digits=9, verbose_name='Base Price')),
                ('is_featured', models.BooleanField(default=False)),
                ('num_visits', models.IntegerField(default=0)),
                ('last_visit', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated on')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='store.category')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('stars', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product Review',
                'verbose_name_plural': 'Product Reviews',
            },
        ),
        migrations.CreateModel(
            name='VariationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Variation Categories - Required if there are options', max_length=255, unique=True)),
                ('slug', models.SlugField(help_text='Category safe URL', max_length=255, unique=True)),
                ('variation_sku', models.CharField(blank=True, help_text='Defaults to slug if left blank', max_length=255, null=True, verbose_name='Variation SKU')),
                ('level', models.PositiveIntegerField(default=0)),
                ('lft', models.PositiveIntegerField(default=0)),
                ('rght', models.PositiveIntegerField(default=0)),
                ('tree_id', models.PositiveIntegerField(default=0)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='store.variationcategory')),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='store.product')),
            ],
            options={
                'verbose_name': 'Variation',
                'verbose_name_plural': 'Variations',
            },
        ),
        migrations.CreateModel(
            name='VariationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_text', models.CharField(blank=True, help_text='Add alternative text', max_length=255, null=True, verbose_name='Alternative text')),
                ('title', models.CharField(help_text='Variation Option - not required', max_length=255, unique=True)),
                ('slug', models.SlugField(help_text='Category safe URL', max_length=255, unique=True)),
                ('option_sku', models.CharField(blank=True, help_text='Defaults to slug if left blank', max_length=255, null=True, verbose_name='Option SKU')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='store.variationcategory')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='store.variationoption')),
            ],
            options={
                'verbose_name': 'Option',
                'verbose_name_plural': 'Options',
            },
        ),
        migrations.CreateModel(
            name='VariationSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_text', models.CharField(blank=True, help_text='Add alternative text', max_length=255, null=True, verbose_name='Alternative text')),
                ('title', models.CharField(help_text='Variation Specifications - not required', max_length=255, unique=True)),
                ('slug', models.SlugField(help_text='Category safe URL', max_length=255, unique=True)),
                ('specification_sku', models.CharField(blank=True, help_text='Defaults to slug if left blank', max_length=255, null=True, verbose_name='Specification SKU')),
                ('description', models.TextField(blank=True, help_text='Not Required', max_length=10000, null=True, verbose_name='Description')),
                ('num_available', models.IntegerField(default=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='store.variationspecification')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='store.variationoption')),
            ],
            options={
                'verbose_name': 'Specification',
                'verbose_name_plural': 'Specifications',
            },
        ),
    ]
