# Generated by Django 5.0.2 on 2024-03-02 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_productvariation_customization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_featured',
        ),
    ]
