# Generated by Django 5.0.2 on 2024-03-03 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_category_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='promotional_price',
        ),
    ]
