# Generated by Django 5.0.2 on 2024-03-15 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_title_variationcategory_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Automatically generated, do not need to upload', null=True, upload_to='uploads/'),
        ),
    ]
